// Configuração de textos por empresa_id para páginas internas da plataforma
const BRANDING_BY_EMPRESA = {
  default: {
    // Textos padrão (empresa_id diferente de 5)
    pacientes: 'Pacientes',
    paciente: 'Paciente',
    consultores: 'Consultores',
    consultor: 'Consultor',
    consultora: 'Consultora',
    agendamentos: 'Agendamentos',
    agendamento: 'Agendamento',
    fechamentos: 'Fechamentos',
    fechamento: 'Fechamento',
    clinicas: 'Clínicas',
    clinica: 'Clínica',
    dashboard: 'Dashboard',
    carteira: 'Carteira',
    carteiraExistente: 'Carteira Existente',
    novosLeads: 'Novos Leads',
    leads: 'Leads',
    lead: 'Lead',
    status: 'Status',
    observacoes: 'Observações',
    documentos: 'Documentos',
    evidencia: 'Evidência',
    evidencias: 'Evidências',
    materiais: 'Materiais',
    perfil: 'Perfil',
    sair: 'Sair',
    editar: 'Editar',
    excluir: 'Excluir',
    salvar: 'Salvar',
    cancelar: 'Cancelar',
    confirmar: 'Confirmar',
    fechar: 'Fechar',
    visualizar: 'Visualizar',
    adicionar: 'Adicionar',
    remover: 'Remover',
    filtrar: 'Filtrar',
    limpar: 'Limpar',
    buscar: 'Buscar',
    exportar: 'Exportar',
    importar: 'Importar',
    configurar: 'Configurar',
    ativo: 'Ativo',
    inativo: 'Inativo',
    pendente: 'Pendente',
    aprovado: 'Aprovado',
    rejeitado: 'Rejeitado',
    concluido: 'Concluído',
    cancelado: 'Cancelado',
    aguardando: 'Aguardando',
    emAndamento: 'Em Andamento',
    finalizado: 'Finalizado',
    // Mensagens específicas
    mensagens: {
      cadastroSucesso: 'Cadastro realizado com sucesso!',
      atualizacaoSucesso: 'Atualização realizada com sucesso!',
      exclusaoSucesso: 'Exclusão realizada com sucesso!',
      erroGenerico: 'Ocorreu um erro. Tente novamente.',
      confirmarExclusao: 'Tem certeza que deseja excluir este item?',
      dadosSalvos: 'Dados salvos com sucesso!',
      operacaoRealizada: 'Operação realizada com sucesso!'
    }
  },

  // Empresa ID 5 - Incorporadora (pacientes → clientes, consultores → corretores)
  5: {
    pacientes: 'Clientes',
    paciente: 'Cliente',
    consultores: 'Corretores',
    consultor: 'Corretor',
    consultora: 'Corretora',
    agendamentos: 'Agendamentos',
    agendamento: 'Agendamento',
    fechamentos: 'Fechamentos',
    fechamento: 'Fechamento',
    clinicas: 'Empreendimentos',
    clinica: 'Empreendimento',
    dashboard: 'Dashboard',
    carteira: 'Carteira',
    carteiraExistente: 'Carteira Existente',
    novosLeads: 'Novos Interessados',
    leads: 'Interessados',
    lead: 'Interessado',
    status: 'Status',
    observacoes: 'Observações',
    documentos: 'Documentos',
    evidencia: 'Evidência',
    evidencias: 'Evidências',
    materiais: 'Materiais',
    perfil: 'Perfil',
    sair: 'Sair',
    editar: 'Editar',
    excluir: 'Excluir',
    salvar: 'Salvar',
    cancelar: 'Cancelar',
    confirmar: 'Confirmar',
    fechar: 'Fechar',
    visualizar: 'Visualizar',
    adicionar: 'Adicionar',
    remover: 'Remover',
    filtrar: 'Filtrar',
    limpar: 'Limpar',
    buscar: 'Buscar',
    exportar: 'Exportar',
    importar: 'Importar',
    configurar: 'Configurar',
    ativo: 'Ativo',
    inativo: 'Inativo',
    pendente: 'Pendente',
    aprovado: 'Aprovado',
    rejeitado: 'Rejeitado',
    concluido: 'Concluído',
    cancelado: 'Cancelado',
    aguardando: 'Aguardando',
    emAndamento: 'Em Andamento',
    finalizado: 'Finalizado',
    // Mensagens específicas
    mensagens: {
      cadastroSucesso: 'Cadastro realizado com sucesso!',
      atualizacaoSucesso: 'Atualização realizada com sucesso!',
      exclusaoSucesso: 'Exclusão realizada com sucesso!',
      erroGenerico: 'Ocorreu um erro. Tente novamente.',
      confirmarExclusao: 'Tem certeza que deseja excluir este item?',
      dadosSalvos: 'Dados salvos com sucesso!',
      operacaoRealizada: 'Operação realizada com sucesso!'
    }
  }
};

export function getBrandingByEmpresa(empresaId) {
  if (!empresaId) return BRANDING_BY_EMPRESA.default;
  return BRANDING_BY_EMPRESA[empresaId] || BRANDING_BY_EMPRESA.default;
}
